basePath: /api/v1
definitions:
  model.CreateProductInput:
    properties:
      name:
        type: string
      price:
        minimum: 0
        type: number
      status:
        enum:
        - active
        - inactive
        type: string
      stock:
        minimum: 0
        type: integer
    required:
    - name
    - price
    - status
    - stock
    type: object
  model.Product:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      status:
        type: string
      stock:
        type: integer
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: Fiber Store Admin API
  title: Fiber Store Admin API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check health of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check health of the API
      tags:
      - Health
  /products:
    get:
      description: Paginated list of products
      parameters:
      - default: 1
        description: page number
        in: query
        name: page
        type: integer
      - default: 20
        description: page size
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: product payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.CreateProductInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create product
      tags:
      - products
swagger: "2.0"
